apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: th98nyivv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: th98nyivv-go 
  name: th98nyivv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: th98nyivv-go 
